apiVersion: v1
kind: Service
metadata:
  name: vector
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
spec:
  ports:
    - name: prom-exporter
      port: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Agent
  type: ClusterIP
